export const ErrorCodes = {
	INVALID_REQUEST: 'INVALID_REQUEST',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	HOTEL_NOT_FOUND: 'HOTEL_NOT_FOUND',
	ROOM_ALREADY_EXISTS: 'ROOM_ALREADY_EXISTS',
	ROOM_NOT_AVAILABLE: 'ROOM_NOT_AVAILABLE',
	INVALID_DATES: 'INVALID_DATES',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export const ROLES = ['customer', 'owner'] as const
export type Role = (typeof ROLES)[number]

export const SALT_ROUNDS = 10
